[package]
edition = "2021"
name = "zamlock"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
rand = "0.8.5"
nalgebra = "0.31.0"
ordered-float = "3.0.0"